# Generated by Django 3.2.4 on 2021-06-27 20:01

from django.db import migrations, models
import imageOCR.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.ImageField(upload_to='pathESP/%Y/%m/%d', validators=[imageOCR.validators.validate_file_extension])),
            ],
        ),
    ]
